### ISSUE TITLE
Flip & speed

### ISSUE THREAD

**Issue by paulgee31** [felix-dumit/FSDAirportFlipLabel#1]
Thanks for writing such a great UI control. it would be really nice if the number of flips and flip speed was configurable.

**Comment by felix-dumit** [comment]
Thanks! I have added some new parameters to control the number of flips and flip speed.
Check out c77ee0f0d1c1e0af6f1791d9b0122e4cee7f5ac0

**Comment by paulgee31** [comment]
Brilliant, thanks for the quick turn around.
